### ISSUE TITLE
Support regexes for `:include` and `:exclude` terms

### ISSUE THREAD

**Issue by crisptrutski** [adzerk-oss/boot-test#21] opened 2015-12-20 21:54 UTC
This is just a standardization / ergonomics drive, as `- f` already gives all the power. 

It would be sweet if symbols still work as literals also. Rather than trying to disambiguate type from CLI, regexes could always need to match the entire namespaces, so there's no real change in usage unless you use wildcards, etc

Not sure if the namespaces should be whittled down from the fileset (like `boot-expectations`), or dynamically (perhaps piggybacking on the `- f` machinery). 

There's a trade-off here - dynamic is more correct, static would be faster (less unnecessary namespaces loaded in the first place)

**Comment by arichiardi** [comment] 2016-09-01 01:26
I started working on this one a bit, but at the moment the `:namespaces` option is necessary for the `test` task: it is an `--include` already. So I was thinking of proposing the alternative that I implemented in `boot.test` (core).

If `:namespaces` is not there, we include all the tests on the classpath and by doing this now we can have `--include` and `--exclude` (or `--invert`) set of regexes to be on par with the other boot tasks.

How does it sound?

**Comment by crisptrutski** [comment] 2016-09-03 08:29
Sounds good to  me! We should probably ping an adzerker though :)

**Comment by daveyarwood** [comment] 2016-10-13 22:24
Sorry I'm late to the party. @arichiardi 's idea sounds good to me, let's do it!

**Comment by seancorfield** [comment] 2017-01-27 02:04
Note that `boot-expectations` uses include / exclude as regexes to filter namespaces before even trying to require them. `boot-test` today requires _all_ namespaces unless you specify a complete set of namespaces to load.

The problem with filters is that it filters the `Var`s _after_ requiring all the namespaces.

I'd be happy to send a PR for `-I` / `--include` / `-X` / `--exclude` to match `boot-expectations` as regexes to filter the names of namespaces _prior to requiring them_.

**Comment by arichiardi** [comment] 2017-01-27 04:09
Probably  the above is also the reason why tests are kind of slow, I would love to see a patch then.

**Comment by seancorfield** [comment] 2017-01-27 05:39
No, I ran some tests with this patch in place and the total time was about 49s without the patch (and using filters) and 45s with the patch (and using include). The pod stuff is a huge time sink, but it's a fairly static overhead -- and for those of us who need the isolation of pods to run tests with different sets of dependencies :)

Mostly the issue is that for any given set of tests I want to run, I don't want _all_ my namespaces loaded -- I just want the subset loaded that my selected tests will load.

**Comment by seancorfield** [comment] 2017-01-27 19:11
This can be closed now as PR #30 provides this and was just merged in (thank you!).

**Closed** 2017-01-27 22:26 UTC
